package ch.uzh.ifi.hase.soprafs21.constant;

public enum Card {
    BANG, BEER, SALOON, WELLSFARGO, STAGECOACH, HIDDEN, GATLING, GENERALSTORE, SCHOFIELD, JAIL, DYNAMITE, REMINGTON,
    CARABINE, VOLCANIC, MUSTANG, BARREL, WINCHESTER, MISSED, APPALOOSA, PANIC, CATBALOU, DUEL, INDIANS
}
